---
version: '3.4'
services:
  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.template:/etc/nginx/templates/default.conf.template
    environment:
      - BASEURL=${BASEURL}
      - PORT_NGINX=${PORT_NGINX}
    network_mode: host
